// Package miniapp is the mini-program (小程序) packaging foundation. A
// mini-program cannot run Go/WASM in its render path — it renders WXML markup
// driven by a JS page model — so QORM targets it by remapping its rendered
// HTML/CSS to WXML/WXSS and emitting a WeChat-style project scaffold.
//
// This is the foundation slice: a valid, viewable project with the app's initial
// UI (static render) and wired tap bindings. Full interactivity (a JS interpreter
// that evaluates QORM bindings/actions and setData) builds on top of it.
package miniapp

import (
	"encoding/base64"
	"fmt"
	"regexp"
	"strings"

	"github.com/qorm/qorm/internal/render"
	"github.com/qorm/qorm/internal/runtime"
)

var (
	onclickRe    = regexp.MustCompile(`onclick="qorm\((\d+)\)"`)
	onclickAnyRe = regexp.MustCompile(`\sonclick="[^"]*"`)
)

// BuildProject renders a QORM app into a WeChat mini-program project as a
// path -> file-content map.
func BuildProject(rt *runtime.Runtime) map[string]string {
	name := rt.App.Name
	if name == "" {
		name = rt.App.ID
	}
	wxml := "<view class=\"qorm-root\">\n" + htmlToWXML(render.Render(rt).HTML) + "\n</view>\n"
	return map[string]string{
		"project.config.json":    projectConfig(name),
		"sitemap.json":           "{\n  \"desc\": \"generated by QORM\",\n  \"rules\": [{ \"action\": \"allow\", \"page\": \"*\" }]\n}\n",
		"app.json":               appJSON(name),
		"app.js":                 "// generated by QORM\nApp({})\n",
		"app.wxss":               themeWXSS(rt.App.Theme),
		"pages/index/index.wxml": wxml,
		"pages/index/index.wxss": "/* page styles — most styling is inline from QORM's renderer */\n",
		"pages/index/index.js":   pageJS(),
		"pages/index/index.json": fmt.Sprintf("{\n  \"navigationBarTitleText\": %q\n}\n", name),
	}
}

// htmlToWXML remaps QORM's rendered HTML fragment to WXML: inline SVG becomes a
// data-URI <image> (WXML can't render <svg>), HTML box/text elements become
// <view>, <img> becomes a closed <image>, onclick becomes a tap binding, and
// WXML-invalid a11y attributes are dropped.
func htmlToWXML(html string) string {
	s := html
	// Inline SVG (icons + charts) -> base64 data-URI <image> — do this first, so
	// the SVG's inner <path>/<rect>/... are encoded, not left as bare markup.
	s = svgRe.ReplaceAllStringFunc(s, svgToImage)
	// Drop attributes WXML has no concept of (role, aria-*).
	s = a11yAttrRe.ReplaceAllString(s, "")
	// onclick="qorm(N)" -> bindtap + data-h=N; strip any other onclick (client-side
	// JS like tab switching won't run in a mini-program's static foundation).
	s = onclickRe.ReplaceAllString(s, `bindtap="onTap" data-h="$1"`)
	s = onclickAnyRe.ReplaceAllString(s, "")
	// Box/interactive/form-container tags with no WXML equivalent -> <view> (QORM
	// styles them fully inline; mapping <button>/<select> avoids default chrome and
	// the WXML parser rejecting <select>/<option>). <input>/<textarea>/<label> are
	// valid WXML and pass through.
	for _, tag := range []string{"div", "button", "span", "p", "a", "select", "option", "optgroup"} {
		s = strings.ReplaceAll(s, "<"+tag+" ", "<view ")
		s = strings.ReplaceAll(s, "<"+tag+">", "<view>")
		s = strings.ReplaceAll(s, "</"+tag+">", "</view>")
	}
	// Images are void in HTML (<img ...> / <img .../>) but WXML needs a real
	// element: <image ...></image>.
	s = imgRe.ReplaceAllString(s, "<image$1></image>")
	return s
}

var (
	imgRe      = regexp.MustCompile(`<img\b([^>]*?)\s*/?>`)
	svgRe      = regexp.MustCompile(`(?s)<svg\b[^>]*>.*?</svg>`)
	svgWHRe    = regexp.MustCompile(`width="([\d.]+)"[^>]*?height="([\d.]+)"`)
	a11yAttrRe = regexp.MustCompile(`\s(?:role|aria-[a-z]+)="[^"]*"`)
)

// svgToImage encodes an inline SVG as a data-URI <image>. Chart SVGs carry
// explicit colors and convert exactly; icon SVGs use currentColor, which has no
// color context inside an isolated image, so it is defaulted to a visible neutral
// (full icon theming on mini-programs is a follow-up).
func svgToImage(svg string) string {
	clean := strings.ReplaceAll(svg, "currentColor", "#3c3c43")
	b64 := base64.StdEncoding.EncodeToString([]byte(clean))
	style := ""
	if m := svgWHRe.FindStringSubmatch(svg); m != nil {
		style = fmt.Sprintf(` style="width:%spx;height:%spx;"`, m[1], m[2])
	}
	return `<image src="data:image/svg+xml;base64,` + b64 + `"` + style + `></image>`
}

func themeWXSS(theme string) string {
	// Design tokens mirror internal/server (Apple default; a manifest theme picks
	// another). WeChat WXSS supports CSS custom properties.
	tokens := `page {
  --accent:#007aff; --on-accent:#fff; --success:#34c759; --danger:#ff3b30; --warning:#ff9500;
  --bg:#f2f2f7; --surface:#fff; --label:#000; --label2:#3c3c4399; --sep:#3c3c4949;
  --fill:#78788033; --radius:12px; --radius-lg:20px;
  background:var(--bg); color:var(--label);
}`
	if theme == "dark" {
		tokens = `page {
  --accent:#0a84ff; --on-accent:#fff; --success:#30d158; --danger:#ff453a; --warning:#ff9f0a;
  --bg:#000; --surface:#1c1c1e; --label:#fff; --label2:#ebebf599; --sep:#54545899;
  --fill:#7676803d; --radius:12px; --radius-lg:20px;
  background:var(--bg); color:var(--label);
}`
	}
	return "/* generated by QORM */\n" + tokens + "\nview { box-sizing:border-box; }\n.qorm-root { min-height:100vh; }\n"
}

func appJSON(name string) string {
	return fmt.Sprintf(`{
  "pages": ["pages/index/index"],
  "window": {
    "navigationBarTitleText": %q,
    "navigationBarBackgroundColor": "#f2f2f7",
    "navigationBarTextStyle": "black",
    "backgroundColor": "#f2f2f7"
  },
  "sitemapLocation": "sitemap.json"
}
`, name)
}

func projectConfig(name string) string {
	return fmt.Sprintf(`{
  "description": "generated by QORM",
  "projectname": %q,
  "appid": "touristappid",
  "setting": { "urlCheck": false, "es6": true, "minified": false },
  "compileType": "miniprogram",
  "libVersion": "latest"
}
`, name)
}

func pageJS() string {
	return `// generated by QORM — mini-program foundation.
// The UI is rendered statically from the QORM app's initial state; tap targets
// carry their handler index in data-h. Full interactivity (evaluating QORM
// actions and setData) is the next slice on top of this foundation.
Page({
  data: {},
  onTap: function (e) {
    var h = e.currentTarget.dataset.h;
    console.log('[qorm] tap handler', h);
  }
})
`
}
