// Package miniapp is the mini-program (小程序) packaging foundation. A
// mini-program cannot run Go/WASM in its render path — it renders WXML markup
// driven by a JS page model — so QORM targets it by remapping its rendered
// HTML/CSS to WXML/WXSS and emitting a WeChat-style project scaffold.
//
// This is the foundation slice: a valid, viewable project with the app's initial
// UI (static render) and wired tap bindings. Full interactivity (a JS interpreter
// that evaluates QORM bindings/actions and setData) builds on top of it.
package miniapp

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/qorm/qorm/internal/render"
	"github.com/qorm/qorm/internal/runtime"
)

var onclickRe = regexp.MustCompile(`onclick="qorm\((\d+)\)"`)

// BuildProject renders a QORM app into a WeChat mini-program project as a
// path -> file-content map.
func BuildProject(rt *runtime.Runtime) map[string]string {
	name := rt.App.Name
	if name == "" {
		name = rt.App.ID
	}
	wxml := "<view class=\"qorm-root\">\n" + htmlToWXML(render.Render(rt).HTML) + "\n</view>\n"
	return map[string]string{
		"project.config.json":    projectConfig(name),
		"sitemap.json":           "{\n  \"desc\": \"generated by QORM\",\n  \"rules\": [{ \"action\": \"allow\", \"page\": \"*\" }]\n}\n",
		"app.json":               appJSON(name),
		"app.js":                 "// generated by QORM\nApp({})\n",
		"app.wxss":               themeWXSS(rt.App.Theme),
		"pages/index/index.wxml": wxml,
		"pages/index/index.wxss": "/* page styles — most styling is inline from QORM's renderer */\n",
		"pages/index/index.js":   pageJS(),
		"pages/index/index.json": fmt.Sprintf("{\n  \"navigationBarTitleText\": %q\n}\n", name),
	}
}

// htmlToWXML remaps QORM's rendered HTML fragment to WXML: HTML box/text elements
// become <view>, images become <image>, and onclick="qorm(N)" becomes a WXML tap
// binding carrying the handler index in a dataset.
func htmlToWXML(html string) string {
	s := html
	// onclick="qorm(N)" -> bindtap + data-h=N (do this before tag remaps).
	s = onclickRe.ReplaceAllString(s, `bindtap="onTap" data-h="$1"`)
	// Box + interactive containers -> <view> (QORM styles them fully inline, so
	// mapping <button> to <view> avoids the platform's default button chrome).
	for _, tag := range []string{"div", "button", "span", "p", "a"} {
		s = strings.ReplaceAll(s, "<"+tag+" ", "<view ")
		s = strings.ReplaceAll(s, "<"+tag+">", "<view>")
		s = strings.ReplaceAll(s, "</"+tag+">", "</view>")
	}
	// Images are void in HTML (<img ...> / <img .../>) but WXML needs a real
	// element: <image ...></image>.
	s = imgRe.ReplaceAllString(s, "<image$1></image>")
	return s
}

var imgRe = regexp.MustCompile(`<img\b([^>]*?)\s*/?>`)

func themeWXSS(theme string) string {
	// Design tokens mirror internal/server (Apple default; a manifest theme picks
	// another). WeChat WXSS supports CSS custom properties.
	tokens := `page {
  --accent:#007aff; --on-accent:#fff; --success:#34c759; --danger:#ff3b30; --warning:#ff9500;
  --bg:#f2f2f7; --surface:#fff; --label:#000; --label2:#3c3c4399; --sep:#3c3c4949;
  --fill:#78788033; --radius:12px; --radius-lg:20px;
  background:var(--bg); color:var(--label);
}`
	if theme == "dark" {
		tokens = `page {
  --accent:#0a84ff; --on-accent:#fff; --success:#30d158; --danger:#ff453a; --warning:#ff9f0a;
  --bg:#000; --surface:#1c1c1e; --label:#fff; --label2:#ebebf599; --sep:#54545899;
  --fill:#7676803d; --radius:12px; --radius-lg:20px;
  background:var(--bg); color:var(--label);
}`
	}
	return "/* generated by QORM */\n" + tokens + "\nview { box-sizing:border-box; }\n.qorm-root { min-height:100vh; }\n"
}

func appJSON(name string) string {
	return fmt.Sprintf(`{
  "pages": ["pages/index/index"],
  "window": {
    "navigationBarTitleText": %q,
    "navigationBarBackgroundColor": "#f2f2f7",
    "navigationBarTextStyle": "black",
    "backgroundColor": "#f2f2f7"
  },
  "sitemapLocation": "sitemap.json"
}
`, name)
}

func projectConfig(name string) string {
	return fmt.Sprintf(`{
  "description": "generated by QORM",
  "projectname": %q,
  "appid": "touristappid",
  "setting": { "urlCheck": false, "es6": true, "minified": false },
  "compileType": "miniprogram",
  "libVersion": "latest"
}
`, name)
}

func pageJS() string {
	return `// generated by QORM — mini-program foundation.
// The UI is rendered statically from the QORM app's initial state; tap targets
// carry their handler index in data-h. Full interactivity (evaluating QORM
// actions and setData) is the next slice on top of this foundation.
Page({
  data: {},
  onTap: function (e) {
    var h = e.currentTarget.dataset.h;
    console.log('[qorm] tap handler', h);
  }
})
`
}
