// Package fonts carries the embedded font assets for the canvas text stack.
//
// The subset font (Source Han Sans SC == Noto Sans CJK SC, SIL OFL-1.1, see
// assets/OFL.txt) is generated by scripts/subset-font.sh and checked into
// assets/. It is compiled into the binary by default (see fonts_cjk.go);
// the qorm_nocjk build tag opts out, in which case this package embeds
// nothing and the binary size is unchanged.
package fonts
