package integration

import (
	"os"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// api/cli.md and api/zh/cli.md are the only hand-written pages of the API
// reference — every other page is generated by the TestAPIRef* tests in this
// package. TestAPIRefCLI guards the hand-written pages against drifting from
// the cmd/qorm implementation, docs -> code only:
//
//  1. every `--flag` token the docs mention must appear as a quoted flag
//     literal somewhere in the cmd/qorm source (all non-test .go files);
//  2. every documented subcommand — `## name` sections, `qorm name` synopsis
//     lines, and the `__name` internal helpers named in prose — must be a
//     case in main()'s dispatch switch;
//  3. the EN and ZH pages must document the same subcommand set.
//
// The reverse direction (code -> docs) is deliberately NOT checked: flag
// literals also appear as arguments to child processes (codesign --force,
// gradle --no-daemon, chromium --new-window, ...), internal sub-process
// helpers and deliberately unlisted flags would all false-positive, and the
// hand-written prose chooses what to surface. This test never rewrites the
// docs (QORM_UPDATE_DOCS has no effect here) — a failure means: fix the docs
// to match the code, or the code to match the docs.

const cliSrcDir = "../../cmd/qorm"

// cliDocFlagAllowlist lists `--tokens` that cli.md may mention without a
// matching flag literal in cmd/qorm (doc-only concepts, not real flags).
// Empty today; add an entry with a reason only when the docs must name a
// token the source cannot contain verbatim.
var cliDocFlagAllowlist = map[string]string{}

// cliSource concatenates the cmd/qorm Go source (excluding _test.go) in
// sorted file order, so a flag literal may live in any file of the package
// (main.go, commands.go, package*.go, shot_*.go, selfupdate.go, ...).
func cliSource(t *testing.T) string {
	t.Helper()
	des, err := os.ReadDir(cliSrcDir)
	if err != nil {
		t.Fatal(err)
	}
	var b strings.Builder
	for _, de := range des {
		n := de.Name()
		if !strings.HasSuffix(n, ".go") || strings.HasSuffix(n, "_test.go") {
			continue
		}
		b.WriteString("\n// file: " + n + "\n")
		b.WriteString(readFile(t, cliSrcDir+"/"+n))
	}
	if b.Len() == 0 {
		t.Fatal("no source files found in " + cliSrcDir)
	}
	return b.String()
}

// cliDispatch returns the set of subcommand names main() dispatches on — the
// quoted case labels of the `switch os.Args[1]` in cmd/qorm/main.go, up to
// the `default:` arm.
func cliDispatch(t *testing.T) map[string]bool {
	t.Helper()
	src := readFile(t, cliSrcDir+"/main.go")
	start := strings.Index(src, "switch os.Args[1] {")
	end := strings.Index(src, "\n\tdefault:")
	if start < 0 || end < 0 || end < start {
		t.Fatal("could not locate the subcommand switch in cmd/qorm/main.go")
	}
	out := map[string]bool{}
	// `[^"]*` (not `+`): the switch contains an empty `""` literal whose two
	// quotes would otherwise pair up with the next string and eat a label.
	for _, m := range regexp.MustCompile(`"([^"]*)"`).FindAllStringSubmatch(src[start:end], -1) {
		if m[1] != "" {
			out[m[1]] = true
		}
	}
	if len(out) < 10 {
		t.Fatalf("dispatch parsing found only %d case labels — parser drift?", len(out))
	}
	return out
}

// cliDoc is the machine-readable surface of one cli.md page.
type cliDoc struct {
	commands map[string]bool // `## name` sections + `qorm name` synopsis lines
	internal map[string]bool // `__name` internal helpers named in prose
	flags    []string        // every `--flag` token mentioned, sorted
}

// parseCLIDoc extracts that surface, tolerant of formatting: only bare
// lowercase command tokens count as commands (so `## Conventions` and
// `## 约定` drop out), synopsis lines are only those inside ``` code fences,
// and flags are plain `--[a-z-]+` tokens wherever they appear.
func parseCLIDoc(t *testing.T, path string) cliDoc {
	t.Helper()
	md := readFile(t, path)
	d := cliDoc{commands: map[string]bool{}, internal: map[string]bool{}}

	// Section headers: `## name`, keeping only all-lowercase tokens.
	nameRe := regexp.MustCompile(`^[a-z][a-z0-9-]*$`)
	for _, m := range regexp.MustCompile(`(?m)^## (\S+)\s*$`).FindAllStringSubmatch(md, -1) {
		if nameRe.MatchString(m[1]) {
			d.commands[m[1]] = true
		}
	}
	// Synopsis lines inside code fences: `qorm <command> ...`.
	inFence := false
	synRe := regexp.MustCompile(`^qorm ([a-z][a-z0-9-]*)\b`)
	for _, ln := range strings.Split(md, "\n") {
		if strings.HasPrefix(strings.TrimSpace(ln), "```") {
			inFence = !inFence
			continue
		}
		if inFence {
			if m := synRe.FindStringSubmatch(ln); m != nil {
				d.commands[m[1]] = true
			}
		}
	}
	// Internal helpers named in prose (the "Internal commands" paragraph).
	for _, m := range regexp.MustCompile(`__[a-z][a-z-]*`).FindAllStringSubmatch(md, -1) {
		d.internal[m[0]] = true
	}
	// Every `--flag` token mentioned anywhere on the page.
	seen := map[string]bool{}
	for _, m := range regexp.MustCompile(`--[a-z][a-z-]*`).FindAllStringSubmatch(md, -1) {
		if !seen[m[0]] {
			seen[m[0]] = true
			d.flags = append(d.flags, m[0])
		}
	}
	sort.Strings(d.flags)

	// Guard the parser itself: a restructured page that silently parses to
	// almost nothing must fail loudly, not pass the drift checks vacuously.
	if len(d.commands) < 10 || len(d.flags) < 20 {
		t.Fatalf("%s: parsed %d commands / %d flags — doc format drift?", path, len(d.commands), len(d.flags))
	}
	return d
}

func TestAPIRefCLI(t *testing.T) {
	src := cliSource(t)
	dispatch := cliDispatch(t)
	const enPath, zhPath = "../../api/cli.md", "../../api/zh/cli.md"
	pages := map[string]cliDoc{
		enPath: parseCLIDoc(t, enPath),
		zhPath: parseCLIDoc(t, zhPath),
	}

	// 1. docs -> code: every documented flag is a real flag literal. The
	// literal is matched quoted, so `--app` cannot ride on `--app-version`.
	for _, path := range []string{enPath, zhPath} {
		d := pages[path]
		for _, f := range d.flags {
			if _, ok := cliDocFlagAllowlist[f]; ok {
				continue
			}
			if !strings.Contains(src, `"`+f+`"`) {
				t.Errorf("%s documents flag %s, but no %q literal exists in cmd/qorm — doc drift, or add it to cliDocFlagAllowlist with a reason", path, f, f)
			}
		}
		// The Conventions section promises `-o`/`--out` and `-p`/`--platform`
		// as synonyms, and `version` lists `-v` as an alias: the short forms
		// must stay real literals too.
		for _, s := range []string{"-o", "-p", "-v"} {
			if !strings.Contains(src, `"`+s+`"`) {
				t.Errorf("%s documents the short flag %s, but no %q literal exists in cmd/qorm", path, s, s)
			}
		}
	}

	// 2. docs -> code: every documented subcommand (public or internal)
	// exists in main()'s dispatch.
	for _, path := range []string{enPath, zhPath} {
		d := pages[path]
		names := make([]string, 0, len(d.commands)+len(d.internal))
		for c := range d.commands {
			names = append(names, c)
		}
		for c := range d.internal {
			names = append(names, c)
		}
		sort.Strings(names)
		for _, c := range names {
			if !dispatch[c] {
				t.Errorf("%s documents subcommand %q, but main() never dispatches it", path, c)
			}
		}
	}

	// 3. EN and ZH stay in lockstep: the same subcommand set on both pages.
	en, zh := pages[enPath], pages[zhPath]
	union := map[string]bool{}
	for c := range en.commands {
		union[c] = true
	}
	for c := range zh.commands {
		union[c] = true
	}
	names := make([]string, 0, len(union))
	for c := range union {
		names = append(names, c)
	}
	sort.Strings(names)
	for _, c := range names {
		if !en.commands[c] {
			t.Errorf("api/zh/cli.md documents subcommand %q but api/cli.md does not", c)
		}
		if !zh.commands[c] {
			t.Errorf("api/cli.md documents subcommand %q but api/zh/cli.md does not", c)
		}
	}
}
